apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  PORT: "8000"
  NODE_ENV: "development"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-auth-service:5432/auth_db"
  REDIS_URL: "redis://redis-auth-service:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
