apiVersion: v1
kind: ConfigMap
metadata:
  name: course-service-config
data:
  PORT: "8003"
  NODE_ENV: "development"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-course-service:5432/course_db"
  REDIS_URL: "redis://redis-course-service:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  USER_SERVICE_URL: "http://user-service-clusterip:8001"
  MEDIA_SERVICE_URL: "http://media-service-clusterip:8002"
