apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: learnsphere

build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: learnsphere/auth-service
      context: services/auth-service
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - infra/k8s/namespace/*.yaml
    - infra/k8s/base/*.yaml
    - infra/k8s/apps/**/*.yaml

deploy:
  kubectl: {}
  defaultNamespace: learnsphere-apps

portForward:
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    port: 443
    localPort: 8443

profiles:
  - name: dev
