apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: learnsphere
  labels: { "app": "learnsphere" }

build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: learnsphere/auth-service
      context: services/auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: "src"
    - image: learnsphere/user-service
      context: services/user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: "src"
    - image: learnsphere/media-service
      context: services/media-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: "src"
    - image: learnsphere/notification-service
      context: services/notification-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: "src"
manifests:
  rawYaml:
    - infrastructure/kubernetes/base/*.yaml
    - infrastructure/kubernetes/services/*.yaml
    - infrastructure/kubernetes/ingress-service.yaml
    - infrastructure/kubernetes/kind-cluster-config.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: ingress-nginx-controller
    namespace: ingress-nginx
    port: 80
    localPort: 8080

profiles:
  - name: dev
