apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-cluster-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: promtail-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: promtail-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-service:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: 'app'
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: 'node_name'
          - source_labels: [__meta_kubernetes_namespace]
            target_label: 'namespace'
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: 'pod'
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: 'container'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail-sa
      initContainers:
        - name: set-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536 || true"]
      containers:
        - name: promtail
          image: grafana/promtail:3.2.1
          args:
            - "-config.file=/etc/promtail/promtail-config.yaml"
          volumeMounts:
            - name: logs
              mountPath: /var/log
            - name: config
              mountPath: /etc/promtail
      volumes:
        - name: logs
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: promtail-config
