services:
  postgres-auth:
    image: postgres:17.5
    container_name: learnsphere-auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1.0-beta.5-management-alpine
    container_name: learnsphere-rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:alpine3.20
    container_name: learnsphere-redis
    ports:
      - "6379:6379"
  postgres-user:
    image: postgres:17.5
    container_name: learnsphere-user-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data:
  user-db-data:
