import { z } from 'zod';

/**
 * @openapi
 * components:
 *   schemas:
 *     CreateOrderPayload:
 *       type: object
 *       required: [courseId]
 *       properties:
 *         courseId:
 *           type: string
 *           format: uuid
 *           description: The unique identifier of the course to be purchased.
 *
 *     CreateOrderResponse:
 *       type: object
 *       properties:
 *         orderId:
 *           type: string
 *           description: The order ID generated by Razorpay.
 *           example: "order_xxxxxxxxxxxxxx"
 *         amount:
 *           type: number
 *           description: The order amount in the smallest currency unit (e.g., paise).
 *           example: 49900
 *         currency:
 *           type: string
 *           description: The currency code (e.g., INR).
 *           example: "INR"
 *     RazorpayWebhookPayload:
 *       type: object
 *       description: "The webhook event payload sent by Razorpay. The structure varies based on the event type."
 *       example:
 *         event: "payment.captured"
 *         payload: { ... }
 */
export const createOrderSchema = z.object({
  body: z.object({
    courseId: z.string().uuid('Invalid course ID format'),
  }),
});
