import {
  Activity,
  AreaChart,
  Award,
  BarChart2,
  Bell,
  BookCopy,
  BookOpen,
  BookOpenCheck,
  Brain,
  Calendar,
  CheckCircle,
  Eye,
  File,
  FileBarChart,
  FileText,
  Folder,
  FolderKanban,
  GraduationCap,
  HeartHandshake,
  Home,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Lightbulb,
  LineChart,
  ListChecks,
  LucideIcon,
  Mail,
  Megaphone,
  MessageSquare,
  Milestone,
  Palette,
  Pencil,
  Plug,
  Presentation,
  Settings,
  Shield,
  Sparkles,
  Trophy,
  User,
  Users,
  UserSquare,
  Workflow,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  Award,
  BarChart2,
  Bell,
  BookCopy,
  BookOpenCheck,
  Calendar,
  CheckCircle,
  Eye,
  FolderKanban,
  HeartHandshake,
  LayoutGrid,
  LineChart,
  Brain,
  MessageSquare,
  Presentation,
  Shield,
  User,
  Users,
  BookOpen,
  FileText,
  Info,
  UserSquare,
  Activity,
  GraduationCap,
  FileBarChart,
  LayoutDashboard,
  ListChecks,
  File,
  AreaChart,
  Settings,
  Mail,
  Pencil,
  Megaphone,
  Lightbulb,
  Plug,
  Palette,
  Home,
  Workflow,
  Trophy,
  Sparkles,
  Folder,
  Milestone,
  LayoutTemplate,
};

export type IconName = keyof typeof iconMap;

//   { href: '#', label: 'Enrolled', value: 'enrolled', icon: 'BookOpenCheck' },
//   { href: '#', label: 'Completed', value: 'completed', icon: 'CheckCircle' },
//   { href: '#', label: 'Recommended', value: 'recommended', icon: 'Sparkles' },
//   { href: '#', label: 'Modules', value: 'modules', icon: 'LayoutTemplate' },
//   { href: '#', label: 'Assignments', value: 'assignments', icon: 'FileText' },
//   { href: '#', label: 'Analytics', value: 'analytics', icon: 'LineChart' },
//   { href: '#', label: 'Comparison', value: 'comparison', icon: 'BarChart2' },
//   { href: '#', label: 'Materials', value: 'materials', icon: 'Folder' },
//   { href: '#', label: 'Study Groups', value: 'study-groups', icon: 'Users' },
//   {
//     href: '#',
//     label: 'Learning Path',
//     value: 'learning-path',
//     icon: 'Milestone',
//   },
// ];
