apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-enrollment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-enrollment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-enrollment
  template:
    metadata:
      labels:
        app: postgres-enrollment
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "enrollment_db"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-enrollment-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-enrollment-service
spec:
  selector:
    app: postgres-enrollment
  ports:
    - port: 5432
      targetPort: 5432
