apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  PORT: "8000"
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-auth-service:5432/auth_db"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  REDIS_URL: "redis://redis-service:6379"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  COOKIE_SECURE: "false"
  COOKIE_DOMAIN: "learnsphere.dev"
  # JWT_SECRET: "kr/RrzjQ31+vfKl0JQxlLHFq4JCraTP8MraNHw"
  # COOKIE_PARSER_SECRET: "8DPz5ooMmG0d8zWMxYnmS2nlf4wOa0hGF77oUri2pMk="
---
apiVersion: batch/v1
kind: Job
metadata:
  name: auth-service-migration-job
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: learnsphere/auth-service
          imagePullPolicy: IfNotPresent
          command: ["node", "dist/db/migrate.js"]
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-secrets
      restartPolicy: Never
  backoffLimit: 2 # retries
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: learnsphere/auth-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: auth-service
      protocol: TCP
      port: 8000
      targetPort: 8000
