apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: learnsphere/course-service
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: course-service-config
            - secretRef:
                name: auth-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: course-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: course-service
  ports:
    - name: http
      protocol: TCP
      port: 8003
      targetPort: 8003
