apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - name: media-service
          image: learnsphere/media-service
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: media-service-config
            - secretRef:
                name: media-secrets
          # readinessProbe:
          #   httpGet:
          #     path: /api/media/health
          #     port: 8002
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 2
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /api/media/health
          #     port: 8002
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          #   timeoutSeconds: 2
          #   failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: media-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: media-service
  ports:
    - name: http
      protocol: TCP
      port: 8002
      targetPort: 8002
