apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: learnsphere/notification-service
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq-service:5672"
            - name: EMAIL_HOST
              value: "live.smtp.mailtrap.io"
            - name: EMAIL_PORT
              value: "2525"
            - name: EMAIL_USER
              value: "api"
            - name: EMAIL_PASS
              value: "3698ee3897787b98e072c683df93dbd1"
            - name: EMAIL_FROM
              value: "hello@demomailtrap.com"
