
apiVersion: v1
kind: ConfigMap
metadata:
  name: learnsphere-configmap
data:
  PORT: "8000"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-auth-service:5432/auth_db"
  REDIS_URL: "redis://redis-auth-service:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  JWT_REFRESH_SECRET: "/51JSQ0CnQA8RvgAhKD43uV8x3yCbggjzwytx9Xa+Jk="
  JWT_SECRET: "OF6dL/ZPyrfGZABnTHY5U2qzQ72nhaUdVuuZsHc2gv0="
  COOKIE_PARSER_SECRET: "LPDaNdF0R+/jeb1OTx/CjBzFqRXdZvL0m6y48aHNGtw="
  USER_SERVICE_URL: "http://user-service-clusterip:8001"
  MEDIA_SERVICE_URL: "http://media-service-clusterip:8002"
  COURSE_SERVICE_URL: "http://course-service-clusterip:8003"
  ENROLLMENT_SERVICE_URL: "http://enrollment-service-clusterip:8004"
  EMAIL_HOST: "live.smtp.mailtrap.io"
  EMAIL_PORT: "2525"
  EMAIL_USER: "api"
  EMAIL_PASS: "3698ee3897787b98e072c683df93dbd1"
  EMAIL_FROM: "hello@demomailtrap.com"
  AWS_REGION: "ap-south-1"
  AWS_RAW_UPLOADS_BUCKET: "learnsphere-raw-uploads-acomjehk"
  AWS_PROCESSED_MEDIA_BUCKET: "learnsphere-processed-media-xt9tcab6"
  AWS_SQS_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/260123625978/s3-media-events-queue"
  AWS_ACCESS_KEY_ID: "AKIATZEETRH5IGO3NOO2"
  AWS_SECRET_ACCESS_KEY: "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"
