apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-auth
  template:
    metadata:
      labels:
        app: redis-auth
    spec:
      containers:
        - name: redis
          image: redis:alpine3.20
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis--auth-service
spec:
  selector:
    app: redis-auth
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-course-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-course
  template:
    metadata:
      labels:
        app: redis-course
    spec:
      containers:
        - name: redis
          image: redis:alpine3.20
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis--course-service
spec:
  selector:
    app: redis-course
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
