apiVersion: v1
kind: ConfigMap
metadata:
  name: media-service-config
data:
  NODE_ENV: "production"
  PORT: "8002"
  AWS_REGION: "ap-south-1"
  AWS_RAW_UPLOADS_BUCKET: "learnsphere-raw-uploads-acomjehk"
  AWS_PROCESSED_MEDIA_BUCKET: "learnsphere-processed-media-xt9tcab6"
  AWS_SQS_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/260123625978/s3-media-events-queue"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - name: media-service
          image: learnsphere/media-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: media-service-config
            - secretRef:
                name: media-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: media-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: media-service
  ports:
    - name: media-service
      protocol: TCP
      port: 8002
      targetPort: 8002
