apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  NODE_ENV: "production"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  EMAIL_HOST: "live.smtp.mailtrap.io"
  EMAIL_PORT: "2525"
  EMAIL_FROM: "hello@demomailtrap.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: learnsphere/notification-service
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: notification-service-secrets
