apiVersion: v1
kind: Service
metadata:
  name: auth-service-clusterip
  namespace: learnsphere-apps
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
