apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}-config
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  REDIS_URL: {{ .Values.config.redisUrl | quote }}
  RABBITMQ_URL: {{ .Values.config.rabbitmqUrl | quote }}