services:
  postgres:
    image: postgres:17.5
    container_name: learnsphere-auth-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: learnsphere-rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:8.2-m01-alpine3.22
    container_name: learnsphere-redis
    ports:
      - "6379:6379"

volumes:
  auth-db-data:
