name: LearnSphere CI/CD - Build and Deploy to EKS
on:
  push:
    tags:
      - "v*"

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 260123625978.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth-service
          - user-service
          - media-service
          - notification-service
          - course-service
          - enrollment-service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_CICD_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY  }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-actions@v3

      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t ${{ env.ECR_REGISTRY }}/learnsphere/${{ matrix.service }}:${{ env.IMAGE_TAG }} \
            -f services/${{ matrix.service }}/Dockerfile \
            services/${{ matrix.service }}

          docker push ${{ env.ECR_REGISTRY }}/learnsphere/${{ matrix.service }}:${{ env.IMAGE_TAG }}
